version: "3.7"

services:
  api-app:
    container_name: api-app
    build: .
    volumes:
      - .:/usr/src/app
    ports: 
      - "8080:8080"
    links: 
      - db
    
  db:
    container_name: api-db
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
